services:
  klar-rm-shop:
#    image: kavore/remnawave-tg-shop:latest
    build: .
    container_name: klar-rm-shop
    hostname: klar-rm-shop
    env_file:
      - .env
    networks:
      - remnawave-network
    volumes:
      - ./locales:/app/locales
    restart: unless-stopped
    depends_on:
      klar-rm-shop-db:
        condition: service_healthy

  klar-rm-shop-db:
    image: postgres:17
    container_name: klar-rm-shop-db
    hostname: klar-rm-shop-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
    volumes:
      - klar-rm-shop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  remnawave-network:
    external: true

volumes:
  klar-rm-shop-db-data:
    name: klar-rm-shop-db-data
