services:
  klar-rm-shop-db:
    image: postgres:17
    container_name: klar-rm-shop-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "5433:5432"
    volumes:
      - klar-rm-shop-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  klar-rm-shop-db-data:
    name: klar-rm-shop-db-data
